---
dist: trusty
before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - curl -fSL https://github.com/wata727/tflint/releases/download/v0.7.0/tflint_linux_amd64.zip -o tflint.zip
  - sudo unzip tflint.zip -d /opt/tflint
  - sudo ln -s /opt/tflint/tflint /usr/bin/tflint
  - rm -f tflint.zip
  - curl -fSL "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o awscli-bundle.zip
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - mkdir -p ~/.aws
  - echo -e "[default]\naws_access_key_id=foo\naws_secret_access_key=bar\nregion=us-west-2" > ~/.aws/config
  - sudo apt-get install graphviz
notifications:
  email: dodomeki@gmail.com
script:
  - make
